name: Build Memorial Texts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: Create Texts
      run: |
        python in-memoriam.py
        mkdir text
        cp *.txt text/
    - name: Upload Texts
      uses: actions/upload-artifact@v1
      with:
        name: InMemoriam
        path: text
